name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare python-for-android (pin tag)
        run: |
          mkdir -p $HOME/.buildozer/android/platform
          cd $HOME/.buildozer/android/platform
          if [ -d python-for-android ]; then
            cd python-for-android
            git fetch --tags origin || true
            git checkout v2023.05.21 || git switch --detach v2023.05.21
          else
            git clone https://github.com/kivy/python-for-android.git python-for-android
            cd python-for-android
            git fetch --tags origin
            git checkout v2023.05.21 || git switch --detach v2023.05.21
          fi
          git rev-parse --short HEAD

      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            zip unzip openjdk-17-jdk \
            libncurses5 libstdc++6 libffi-dev libssl-dev \
            autoconf automake libtool pkg-config zlib1g-dev

      - name: Install Android SDK cmdline-tools
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip curl

          mkdir -p $HOME/android-sdk/cmdline-tools
          cd $HOME

          curl -o cmdline-tools.zip https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
          unzip cmdline-tools.zip

          mv cmdline-tools $HOME/android-sdk/cmdline-tools/latest

          echo "$HOME/android-sdk/cmdline-tools/latest/bin" >> $GITHUB_PATH
          echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
          echo "ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV


      - name: Install buildozer & deps
        run: |
          python -m pip install --upgrade pip
          # берем buildozer напрямую из репо (последняя версия)
          python -m pip install git+https://github.com/kivy/buildozer.git
          # Cython нужен p4a-коли? лучше заранее установить
          python -m pip install cython==0.29.36

      - name: Accept Android licenses
        run: |
          yes | sdkmanager --licenses



      - name: Build APK
        run: |
          buildozer android debug
          

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: BrainUp-APK
          path: bin/*.apk
